
name: 'salesmotion_dbt'
version: '1.0.0'

profile: 'salesmotion_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  salesmotion_dbt:
    +materialized: view
    staging:
      +materialized: view
      +schema: stg
      +tags: ["staging"]
    intermdiate:
      +materialized: view
      +schema: int
      +tags: ["intermediate"]
    marts:
      +materialized: table
      +schema: mart
      +tags: ["mart"]

# tag nous permet de lancer des commande spécifiques, ex : dbt run --select tag:staging
